### ISSUE TITLE
conversion of cuda tensors

### ISSUE THREAD

**Issue by simonm3** [fastai/fastprogress#16]
I am getting an error at the end of a fastai training loop.

> can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Seems a bit weird that pytorch does not just log a warning and do the conversion for you. However as they don't it would be useful to add ".cpu()" in the progress bar or earlier. This is my stack trace:

TypeError                                 Traceback (most recent call last)
<ipython-input-9-a888de4df517> in <module>
----> 1 learn.fit(1, lr=.01)

<ipython-input-8-716d8867e71f> in fit(self, epochs, lr, callbacks)
      8         callbacks = [cb(self) for cb in self.callback_fns] + listify(callbacks)
      9         fit(epochs, self.model, self.loss_func, opt=self.opt, data=self.data, metrics=self.metrics,
---> 10             callbacks=self.callbacks+callbacks)
     11 
     12 # create and fit model

~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/basic_train.py in fit(epochs, model, loss_func, opt, data, callbacks, metrics)
     87     except Exception as e:
     88         exception = e
---> 89         raise e
     90     finally: cb_handler.on_train_end(exception)
     91 

~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/basic_train.py in fit(epochs, model, loss_func, opt, data, callbacks, metrics)
     84                                        cb_handler=cb_handler, pbar=pbar)
     85             else: val_loss=None
---> 86             if cb_handler.on_epoch_end(val_loss): break
     87     except Exception as e:
     88         exception = e

~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/callback.py in on_epoch_end(self, val_loss)
    250                 met.on_epoch_end(**self.state_dict)
    251                 self.state_dict['last_metrics'].append(met.metric)
--> 252         return np.any(self('epoch_end', False))
    253 
    254     def on_train_end(self, exception:Union[bool,Exception])->None:

~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/callback.py in __call__(self, cb_name, call_mets, **kwargs)
    185         "Call through to all of the `CallbakHandler` functions."
    186         if call_mets: [getattr(met, f'on_{cb_name}')(**self.state_dict, **kwargs) for met in self.metrics]
--> 187         return [getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs) for cb in self.callbacks]
    188 
    189     def on_train_begin(self, epochs:int, pbar:PBar, metrics:MetricFuncList)->None:

~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/callback.py in <listcomp>(.0)
    185         "Call through to all of the `CallbakHandler` functions."
    186         if call_mets: [getattr(met, f'on_{cb_name}')(**self.state_dict, **kwargs) for met in self.metrics]
--> 187         return [getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs) for cb in self.callbacks]
    188 
    189     def on_train_begin(self, epochs:int, pbar:PBar, metrics:MetricFuncList)->None:

~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/train.py in on_epoch_end(self, n_epochs, last_metrics, **kwargs)
     55             x_bounds = (0, (n_epochs - len(rec.nb_batches)) * rec.nb_batches[-1] + len(rec.losses))
     56             y_bounds = (0, max((max(Tensor(rec.losses)), max(Tensor(rec.val_losses)))))
---> 57             rec.pbar.update_graph([(iters, rec.losses), (val_iter, rec.val_losses)], x_bounds, y_bounds)
     58             return False
     59 

~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastprogress/fastprogress.py in update_graph(self, graphs, x_bounds, y_bounds)
    189         self.ax.legend(loc='upper right')
    190         if x_bounds is not None: self.ax.set_xlim(*x_bounds)
--> 191         if y_bounds is not None: self.ax.set_ylim(*y_bounds)
    192         with self.out:
    193             clear_output(wait=True)

~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/matplotlib/axes/_base.py in set_ylim(self, bottom, top, emit, auto, ymin, ymax)
   3474                  'bottom=%s, top=%s') % (bottom, top), stacklevel=2)
   3475 
-> 3476         bottom, top = mtransforms.nonsingular(bottom, top, increasing=False)
   3477 
   3478         if self.get_yscale() == 'log':

~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/matplotlib/transforms.py in nonsingular(vmin, vmax, expander, tiny, increasing)
   2887     """
   2888 
-> 2889     if (not np.isfinite(vmin)) or (not np.isfinite(vmax)):
   2890         return -expander, expander
   2891 

~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/tensor.py in __array__(self, dtype)
    430     def __array__(self, dtype=None):
    431         if dtype is None:
--> 432             return self.numpy()
    433         else:
    434             return self.numpy().astype(dtype, copy=False)

TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by simonm3** [comment]
p.s. quite surprised nobody else has logged this. I suspect it is because historically the way to switch between cpu and cuda was to pass the device around and have .to(device) statements everywhere. I am using default tensor type of cuda float. This is really convenient as it allows one to switch between cpu and cuda with one line of code at the start.

**Comment by sgugger** [comment]
I'm not sure this is an issue of fastprogress. You should go on fastai of the problem is still there.

**Comment by shuxp** [comment]
> p.s. quite surprised nobody else has logged this. I suspect it is because historically the way to switch between cpu and cuda was to pass the device around and have .to(device) statements everywhere. I am using default tensor type of cuda float. This is really convenient as it allows one to switch between cpu and cuda with one line of code at the start.

I met the same problem, I check my pytorch version, which is 1.0.0, which I compiled from source. I don't know if it matters.

**Comment by simonm3** [comment]
I have just submitted a pull request to fastai which will fix. It is just a
one line change.
