### ISSUE TITLE
Not Working in VisualStudioCode/Python extension

### ISSUE THREAD

**Issue by loretoparisi** [fastai/fastprogress#18]
Since end of October, VisualStudioCode supports python, IPython and Jupyter Notebook - see [this](https://github.com/loretoparisi/jupyter-notebook-visualstudio-code-python) repo as an example. Now running the progress bar example

```python
#%%
from fastprogress import master_bar, progress_bar
from time import sleep
mb = master_bar(range(10))
for i in mb:
    for j in progress_bar(range(100), parent=mb):
        sleep(0.01)
        mb.child.comment = f'second bar stat'
    mb.first_bar.comment = f'first bar stat'
    mb.write(f'Finished loop {i}.')
    #mb.update_graph(graphs, x_bounds, y_bounds)
```

does not properly update the UI, thus resulting in this output.

<img width="1383" alt="schermata 2018-11-16 alle 10 43 31" src="https://user-images.githubusercontent.com/163333/48613591-7a383f80-e98c-11e8-87b9-05f55ba9f381.png">

The animation is now showed in the UI basically. Runnable example is [here](https://github.com/loretoparisi/jupyter-notebook-visualstudio-code-python/blob/master/progressbar.py)

**Comment by sgugger** [comment]
Yeah, I guess it's the same kind of IPython as Spyder, where it doesn't work properly as well. You can force console behavior by doing:
```
from fast_progress import force_console_behavior
master_bar, progress_bar = force_console_behavior()
```
and if using them in fastai you will maybe need to do:
```
fastai.basic_train.master_bar, fastai.basic_train.progress_bar = master_bar, progress_bar
```

**Comment by loretoparisi** [comment]
@sgugger thanks! So doing like that

```python
#%%
from fastprogress import master_bar, progress_bar
from fastprogress import force_console_behavior
master_bar, progress_bar = force_console_behavior()
from time import sleep
mb = master_bar(range(10))
for i in mb:
    for j in progress_bar(range(100), parent=mb):
        sleep(0.01)
        mb.child.comment = f'second bar stat'
    mb.first_bar.comment = f'first bar stat'
    mb.write(f'Finished loop {i}.')
    #mb.update_graph(graphs, x_bounds, y_bounds)
```

it shows the progress bar, but on multiple new lines for each execution, while it should be rendered on the same line I guess

<img width="681" alt="schermata 2018-11-16 alle 21 30 46" src="https://user-images.githubusercontent.com/163333/48645767-e5aefb00-e9e6-11e8-9039-2c2a5f61ad7d.png">

**Comment by sgugger** [comment]
Ugh, if they don't support the return character in string to update a text, they don't really support python... There's nothing much I can do in this case.

**Comment by loretoparisi** [comment]
@sgugger thank you, I have submitted an issue to VSCode in the meanwhile.

**Comment by loretoparisi** [comment]
@sgugger so I have moved this issue to VS python extension code to get proper support. I would keep this open until there is more info about it if you don't mind. Thank you!

**Comment by sgugger** [comment]
Looks like the issue was fixed on the VSCode side so we can close this.
