### ISSUE TITLE
Can not continue to see the message using table = False written in progress runtime

### ISSUE THREAD

**Issue by newfyu** [fastai/fastprogress#19]
```
from fastprogress import master_bar, progress_bar
from time import sleep
mb = master_bar(range(10))
for i in mb:
    for j in progress_bar(range(100), parent=mb):
        sleep(0.01)
        mb.child.comment = f'second bar stat'
    mb.first_bar.comment = f'first bar stat'
    mb.write(f'no_table{i}.') # This message cannot be displayed continuously at runtime
    mb.write(f'use_table{i}',table=True)
```

In the notebook，I tried to insert some messages with write() between the two progress bars, and the message written with table=False would be overwritten with the message written by table=True. While all can be displayed at the end of the run, but I can not continue to see the message using table = False written in progress runtime.

**Comment by sgugger** [comment]
The intended behavior is to have either a table or a text, but not both at the same time. You can adapt the source code if you want to do some custom mix ;)
