### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'update'

### ISSUE THREAD

**Issue by liamflynn1989** [fastai/fastprogress#20]
Running the example from https://pypi.org/project/fastprogress/ below:

```
from fastprogress import master_bar, progress_bar
from time import sleep
mb = master_bar(range(10))
for i in mb:
    for j in progress_bar(range(100), parent=mb):
        sleep(0.01)
        mb.child.comment = f'second bar stat'
    mb.first_bar.comment = f'first bar stat'
    mb.write(f'Finished loop {i}.')
    #mb.update_graph(graphs, x_bounds, y_bounds)
```

returns the error:

`AttributeError: 'NoneType' object has no attribute 'update'`

I have tried this on both a Mac and PC running Python 3.6.1

**Comment by thebigwish** [comment]
This is a big one

**Comment by thebigwish** [comment]
Have you tried updating to latest version of pip and python?

**Comment by chrisnold1** [comment]
I just tried it in Python 3.6.2 with PIP version 18 and it worked fine for me.

**Comment by liamflynn1989** [comment]
This is resolved in Python 3.7

**Comment by DerekChia** [comment]
i got this error and i'm on fastprogress 0.1.18, fastai 1.0.39, python 3.6.7 and pip 18.1

What is the way to solve this?

**Comment by arnabdutta2194** [comment]
AttributeError: 'NoneType' object has no attribute 'update' Python 3.8
