### ISSUE TITLE
Reloading of Browser looses all of the output in  jupyter notebook 

### ISSUE THREAD

**Issue by manugarri** [fastai/fastprogress#22]
Using the fastai library, I am using a computing EC2 machine with a jupyter notebook to train models using fastai lib.

However, when I reload the notebook, the cells that where running while I closed the browser tab do not display any output.

Is there any way to fix this? Maybe setting some top level config in the notebook to revert to the console output?

Im using Ubuntu 18.04 LTS chrome.

**Comment by sgugger** [comment]
I'm not sure there is anything to be done about that, the console output would give the same problem. If you want to run your notebook without having to worry about closing your browser, the only solution I know of is using a VNC server.

**Comment by sgugger** [comment]
Closing this issue since no one seems to have any idea on how to fix it.
