### ISSUE TITLE
Interactive demo for `fastprogress` code examples

### ISSUE THREAD

**Issue by martinzugnoni** [fastai/fastprogress#23]
Hello @fastai!

I've been trying `fastprogress` recently and found it really interesting. We are also thinking about adding it to our curriculum at https://rmotr.com/ (co-founder and teacher here). It improves the UX a lot while working with long running training processes.

While looking at the code examples in the README file I thought it would be great to provide some interactive demo that people can use to play with the library before committing to download and install it locally.

> A demo is worth a thousand words 😉

I spent a few minutes compiling `fastprogress` examples into a Jupyter Notebook file, and adapted it in a way that we can open it with a small service we have at RMOTR to launch Jupyter environments online. Note that `fastprogress` (and other libraries like `numpy`) are already installed when the env is loaded, so people can start using it right away.

The result is what you can see in my fork of the repo (see the new "Demo" section):
https://github.com/martinzugnoni/fastprogress

Do you think that having such interactive demo would help people to know and use `fastprogress`?
Let's use this issue as a kick off to start a discussion. Nothing here is written in stone and we can change everything as you wish.

I hope you like it, and I truly appreciate any feedback.

thanks.

**Comment by jph00** [comment]
We're very interested in having a way to open our notebooks in a free cloud service, although what we really are looking for is something that works with the fastai library in general, not just the fastprogress library. In particular, it would be great to be able to run these notebooks:

https://github.com/fastai/fastai/tree/master/docs_src

Is that something you'd be interested in supporting? If so, we could certainly discussing adding links from our docs to your service, and could give you some pointers on what's required to get it working.

**Comment by martinzugnoni** [comment]
Thanks @jph00. I will try to run these notebooks in https://notebooks.rmotr.com/ to see if I find any technical issues or difficulties. It would be great to be able to integrate `fastai`. Will come back to you either with news or questions 😉.

**Comment by jph00** [comment]
Closing this since it's been a while. Feel free to reopen if there's any update.
