### ISSUE TITLE
Not working in jupyter console

### ISSUE THREAD

**Issue by levinas** [fastai/fastprogress#26]
Is there a way to get console behavior in Jupyter console?  Currently it just says <IPython.core.display.HTML object>

```
Jupyter console 6.0.0

Python 3.7.1 (default, Dec 14 2018, 19:28:38)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: get_ipython().__class__.__name__
Out[1]: 'ZMQInteractiveShell'

In [2]: from fastprogress import master_bar, progress_bar
      : from time import sleep
      : mb = master_bar(range(10))
      : for i in mb:
      :     for j in progress_bar(range(100), parent=mb):
      :         sleep(0.01)
      :
<IPython.core.display.HTML object>
```

**Comment by sgugger** [comment]
If you find me a way to discriminate between jupyter console and jupyter notebook, I'll happily implement it, but `get_ipython().__class__.__name__` gives the same as for a Jupyter notebook.
A workaround that always work is to call
```
from fastprogress import force_console_behavior
master_bar,progress_bar = force_console_behavior()
```

**Comment by stas00** [comment]
This?
https://github.com/fastai/fastai/blob/master/fastai/utils/env.py#L5

**Comment by sgugger** [comment]
Eh, what does each part of this test return for you @levinas ?

**Comment by levinas** [comment]
@sgugger Looks like the first part of is_in_ipython() would work for me. I mostly use this in emacs, where `python-shell-interpreter` is set to`jupyter-console`. 

```
In [3]: program_name
Out[9]: 'emacs'

In [11]: 'JPY_PARENT_PID'   in os.environ
Out[11]: True
```

**Comment by sgugger** [comment]
Ok, I've got colab handled on the side and what is the result for jupyter lab, do you know @stas00 ? The notebook behavior works in those three.

**Comment by stas00** [comment]
```
import os
program_name = os.path.basename(os.getenv('_', ''))
print(program_name)
'JPY_PARENT_PID'   in os.environ
```
on colab returns:
```
forever
True
```

**Comment by sgugger** [comment]
Just tried jupyter lab and I get 'jupyter' as a program name. I also get this in the jupyter lab console though, so it's not discriminating.

**Comment by stas00** [comment]
And I suppose the user can modify `program_name` in any way she wants, so this would be unreliable anyway.

The main SO thread discussing this issue is [here](https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook)

Some other propositions from that thread that may fit well here are:

```
def isnotebook():
    try:
        shell = get_ipython().__class__.__name__
        if shell == 'ZMQInteractiveShell':
            return True   # Jupyter notebook or qtconsole
        elif shell == 'TerminalInteractiveShell':
            return False  # Terminal running IPython
        else:
            return False  # Other type (?)
    except NameError:
        return False      # Probably standard Python interpreter
```
which most likely is what you're after.

and another approach:
```
import sys

def in_notebook():
    """
    Returns ``True`` if the module is running in IPython kernel,
    ``False`` if in IPython shell or other Python shell.
    """
    return 'ipykernel' in sys.modules

def ipython_info():
    ip = False
    if 'ipykernel' in sys.modules:
        ip = 'notebook'
    elif 'IPython' in sys.modules:
        ip = 'terminal'
    return ip
```
perhaps these need to be combined for better detection?

and we probably should add the working version to fastai's `env.py` as it'd come handy in the future.

**Comment by sgugger** [comment]
The first one is what is currently used, and it fails for jupyter console since we have this issue.

@levinas can you give us the results of the second block of tests: 
```
'ipykernel' in sys.modules
'IPython' in sys.modules
```
in your environment?

**Comment by levinas** [comment]
My environment returned True for both tests. @sgugger

**Comment by stas00** [comment]
Yes, for the notebook, what about the console? Should be false for the first one for console.

**Comment by levinas** [comment]
```
Jupyter console 5.2.0

Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 30 2017, 18:42:57)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sys

In [2]: 'ipykernel' in sys.modules
Out[2]: True

In [3]: 'IPython' in sys.modules
Out[3]: True
```

**Comment by stas00** [comment]
OK, so both are the same then. Can you perhaps inquire with the jupyter console developers at how we can tell programmatically jupyter console from jupyter notebook? Thank you!

**Comment by levinas** [comment]
Would it be possible to provide an environment flag that I could set to force console behavior? I'm using the progress bar through fast.ai so I'm not sure how to call `force_console_behavior()`..

**Comment by indigoviolet** [comment]
> Would it be possible to provide an environment flag that I could set to force console behavior? I'm using the progress bar through fast.ai so I'm not sure how to call `force_console_behavior()`..

Perhaps this could be implemented similar to `%matplotlib inline`? I'm having the same issue (using through fastai).

**Comment by sgugger** [comment]
This issue as a workaround with `force_console_behavior` and it looks like jupyter console has not replied to the issue on their repo, so closing since there is nothing we can do.
