### ISSUE TITLE
Passing pymongo query to progress_bar

### ISSUE THREAD

**Issue by ecatkins** [fastai/fastprogress#27]
Trying to pass a pymongo query to progress_bar results in the error below. I can fix this by passing my pymongo query in as a list i.e. `progress_bar(list(x))` 

But would it be possible/desirable to handle this coercion internally to fastprogress?

```
/opt/anaconda3/lib/python3.7/site-packages/fastprogress/fastprogress.py in __init__(self, gen, total, display, leave, parent, auto_update)
    144 class NBProgressBar(ProgressBar):
    145     def __init__(self, gen, total=None, display=True, leave=True, parent=None, auto_update=True):
--> 146         self.progress = html_progress_bar(0, len(gen) if total is None else total, "")
    147         super().__init__(gen, total, display, leave, parent, auto_update)
    148 

TypeError: object of type 'Cursor' has no len()
```

**Comment by sgugger** [comment]
Just to be sure I understand properly, you'd like fastprogress to try len(list(gen)) if len(gen) fails, is that correct?

**Comment by ecatkins** [comment]
Yes, ideally I would think the library should work with any iterable. But there may be a good reason this isn't the case?

**Comment by sgugger** [comment]
It does take an iterable, but if it doesn't have any `__len__` function, the library expects you to pass the length manually in `total` (like for a file download). Going silently over the iterator to find its length in every case isn't really something I'd like to do.

**Comment by ecatkins** [comment]
I see! I didn't understand that was the intention of the `total` variable
