### ISSUE TITLE
name 'HTML' is not defined

### ISSUE THREAD

**Issue by tuzhucheng** [fastai/fastprogress#32]
When I'm trying to run the following from fast.ai v3 lesson 3 IMDB notebook:

```py
data_lm = TextDataBunch.from_csv(path, 'texts.csv')
```

I get the following error:

```
/opt/conda/lib/python3.7/site-packages/fastprogress/fastprogress.py in on_iter_begin(self)
    160 
    161     def on_iter_begin(self):
--> 162         if self.display: self.out = display(HTML(self.progress), display_id=True)
    163         self.is_active=True
    164 

NameError: name 'HTML' is not defined
```

Here are the library versions:
* fastai-1.0.52
* fastprogress-0.1.21

**Comment by sgugger** [comment]
That is really weird. In which environment are you? Normally you should have seen a warning if HTML wasn't properly imported.

**Comment by tuzhucheng** [comment]
I'm obtained this in the Jupyter Lab environment. However, even if I change from Jupyter Lab to Jupyter notebook by changing `/lab` to `/tree` I still get this error.

**Comment by sgugger** [comment]
In jupyter lab, you need to type this after installing ipywidgets
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
More generally, it seems there is something broken with your installation of [ipywidgets](https://ipywidgets.readthedocs.io/en/stable/user_install.html), try reinstalling it?

**Comment by sgugger** [comment]
This has not been addressed in a while, so closing.
