### ISSUE TITLE
Support for JupyterLab

### ISSUE THREAD

**Issue by H4dr1en** [fastai/fastprogress#33]
Hi, is fastprogress officially supporting Jupyter Lab?
For now, calling progress_bar doesn't show the bar:

![image](https://user-images.githubusercontent.com/16240134/58783307-e4d76280-85e0-11e9-8b28-4a740b6aa48c.png)

If no, it would be good to integrate it to Jupyter Lab as more and more people are shifting to Lab.

**Comment by sgugger** [comment]
progressbar is completely supported in jupyter lab, you just need to run an additional line 
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
to have the widgets properly installed (that's on ipywidgets, not on fastprogress)
