### ISSUE TITLE
Updating a multiprocess progress_bar

### ISSUE THREAD

**Issue by fonnesbeck** [fastai/fastprogress#39]
I'm trying to replace a `tqdm` progress bar with a `fastprogress` bar. However, its not clear how to implement it for multiprocessing. Since `gen` is a required argument there does not seem to be an obvious way to allow processes to update the bar. Any instructions, or a pointer to an example, would be helpful.

**Comment by sgugger** [comment]
You can use the update function a bit like a tqdm progress bar, see this [download function](https://github.com/fastai/fastai/blob/3a6c12040612fb53246ec3aff10cad7146747852/fastai/core.py#L196) for instance.

**Comment by fonnesbeck** [comment]
Is it possible to have child progress bars for each parallel process, and have them update independently, or can the child bars only work in serial?

**Comment by sgugger** [comment]
No, this is not build for this use case. It just does two nested progress bar, one child and on parent.
