### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'update' using Python 3.7

### ISSUE THREAD

**Issue by zivanfi** [fastai/fastprogress#41]
Issue #20 already described this problem for Python versions pre-3.7, but for me it also happens in Python 3.7. Even the history of issue #24 (which just bumped the version requirement) shows that the connection between the Python version and the bug is uncertain.

System info:

<details> 
  <summary>(click triangle on the left to expand/collapse)</summary>
  <p>

```text
=== Software === 
python        : 3.7.3
fastai        : 1.0.59
fastprogress  : 0.1.21
torch         : 1.3.0
nvidia driver : 418.40
torch cuda    : 10.1.243 / is **Not available** 

=== Hardware === 
nvidia gpus   : 1
Have 1 GPU(s), but torch can't use them (check nvidia driver) 

=== Environment === 
platform      : Linux-4.14.133-113.112.amzn2.x86_64-x86_64-with-Ubuntu-18.04-bionic
distro        : #1 SMP Tue Jul 30 18:29:50 UTC 2019
conda env     : python3.6
python        : /usr/bin/python3.7
sys.path      : 
/usr/lib/python37.zip
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/home/username/.local/lib/python3.7/site-packages
/home/username/.conda/envs/python3.7/lib/python3.7/site-packages
/usr/local/lib/python3.7/dist-packages
/usr/lib/python3/dist-packages
/opt/cloudera/parcels/CDH/lib/spark/python
/home/username/.ipython
```
  </p>
</details>

Stack trace:

<details> 
  <summary>(click triangle on the left to expand/collapse)</summary>
  <p>

```
/home/username/.local/lib/python3.7/site-packages/fastai/train.py in fit_one_cycle(learn, cyc_len, max_lr, moms, div_factor, pct_start, final_div, wd, callbacks, tot_epochs, start_epoch)
     21     callbacks.append(OneCycleScheduler(learn, max_lr, moms=moms, div_factor=div_factor, pct_start=pct_start,
     22                                        final_div=final_div, tot_epochs=tot_epochs, start_epoch=start_epoch))
---> 23     learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
     24 
     25 def fit_fc(learn:Learner, tot_epochs:int=1, lr:float=defaults.lr,  moms:Tuple[float,float]=(0.95,0.85), start_pct:float=0.72,

/home/username/.local/lib/python3.7/site-packages/fastai/basic_train.py in fit(self, epochs, lr, wd, callbacks)
    198         else: self.opt.lr,self.opt.wd = lr,wd
    199         callbacks = [cb(self) for cb in self.callback_fns + listify(defaults.extra_callback_fns)] + listify(callbacks)
--> 200         fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
    201 
    202     def create_opt(self, lr:Floats, wd:Floats=0.)->None:

/home/username/.local/lib/python3.7/site-packages/fastai/basic_train.py in fit(epochs, learn, callbacks, metrics)
     97             cb_handler.set_dl(learn.data.train_dl)
     98             cb_handler.on_epoch_begin()
---> 99             for xb,yb in progress_bar(learn.data.train_dl, parent=pbar):
    100                 xb, yb = cb_handler.on_batch_begin(xb, yb)
    101                 loss = loss_batch(learn.model, xb, yb, learn.loss_func, learn.opt, cb_handler)

/home/username/.local/lib/python3.7/site-packages/fastprogress/fastprogress.py in __init__(self, gen, total, display, leave, parent, auto_update)
    157     def __init__(self, gen, total=None, display=True, leave=True, parent=None, auto_update=True):
    158         self.progress = html_progress_bar(0, len(gen) if total is None else total, "")
--> 159         super().__init__(gen, total, display, leave, parent, auto_update)
    160 
    161     def on_iter_begin(self):

/home/username/.local/lib/python3.7/site-packages/fastprogress/fastprogress.py in __init__(self, gen, total, display, leave, parent, auto_update)
     55         else:
     56             self.leave,self.display=False,False
---> 57             parent.add_child(self)
     58         self.comment = ''
     59         if not self.auto_update:

/home/username/.local/lib/python3.7/site-packages/fastprogress/fastprogress.py in add_child(self, child)
    207         self.child = child
    208         self.inner_dict['pb2'] = self.child.progress
--> 209         self.show()
    210 
    211     def show(self):

/home/username/.local/lib/python3.7/site-packages/fastprogress/fastprogress.py in show(self)
    214         to_show = [name for name in self.order if name in self.inner_dict.keys()]
    215         self.html_code = '\n'.join([self.inner_dict[n] for n in to_show])
--> 216         self.out.update(HTML(self.html_code))
    217 
    218     def write(self, line, table=False):

AttributeError: 'NoneType' object has no attribute 'update'
```
  </p>
</details>

I may be mistaken, but it seems to me that:
- `self.out` is only set in `NBMasterBar.on_iter_begin`, but `NBMasterBar.show` may try use it regardless.
- `NBMasterBar.show` can be called by `NBMasterBar.add_child`, which happens from `ProgressBar.__init__` as `parent.add_child(self)`.

**Comment by sgugger** [comment]
I can't do anything to fix this without a reproducible example. If you have some code that generates this bug, it would be most helpful.

**Comment by zivanfi** [comment]
I was just doing [lesson 1 of the fast.ai course](https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson1-pets.ipynb) and got this error.

Even if this example does not reproduce the error for you, considering that self.out may not get initalized in every execution path, wouldn't cheking for self.out not being None before calling a method on it be a good safety measure?

**Comment by sgugger** [comment]
Doing lesson 1 of the fastai course is not a reproducible example as it runs completely fine for me and many other people, so there is another reason this fails for you. Adding a check of is not None is just going to make the progress bar not be shown so it's not really a solution.

fastai always beings the iteration of the master bar before adding a child, for some reason, creating the `out` attribute silently fails and returns None. What does
```
from IPython.display import clear_output, display, HTML
out = display(HTML(some_html_code), display_id=True)
```
do for you?

**Comment by tunner007** [comment]
Even i am facing same issue, can you please suggest how can i remove the progress bar... 
I can run it in terminal with no issues but when i run a job in cloudera it gives me same error.

**Comment by tunner007** [comment]
> Doing lesson 1 of the fastai course is not a reproducible example as it runs completely fine for me and many other people, so there is another reason this fails for you. Adding a check of is not None is just going to make the progress bar not be shown so it's not really a solution.
> 
> fastai always beings the iteration of the master bar before adding a child, for some reason, creating the `out` attribute silently fails and returns None. What does
> 
> ```
> from IPython.display import clear_output, display, HTML
> out = display(HTML(some_html_code), display_id=True)
> ```
> 
> do for you?

No ERROR when i tried running it separately

**Comment by tunner007** [comment]
> Doing lesson 1 of the fastai course is not a reproducible example as it runs completely fine for me and many other people, so there is another reason this fails for you. Adding a check of is not None is just going to make the progress bar not be shown so it's not really a solution.
> 
> fastai always beings the iteration of the master bar before adding a child, for some reason, creating the `out` attribute silently fails and returns None. What does
> 
> ```
> from IPython.display import clear_output, display, HTML
> out = display(HTML(some_html_code), display_id=True)
> ```
> 
> do for you?

![image](https://user-images.githubusercontent.com/46425391/68368634-7d5caa80-015e-11ea-9d8f-100f47440135.png)

**Comment by tunner007** [comment]
I think problem is with below code, in **few cases of "ZMQInteractiveShell"** ipython will **not generate display_id** due to which "out" becomes "None" & later it cannot update. For jupyter notebook it works fine but with cloudera i was facing this issue. So for my case i simply added a check if i am not able to generate display_id **isnotebook becomes False** which solves my problem.

I am noob here :P so will leave rest on you guys to clear it out.

def isnotebook():
    try:
        from google import colab
        return True
    except: pass
    try:
        shell = get_ipython().__class__.__name__
        if shell == 'ZMQInteractiveShell':
            ##added check here for display_id##
            return True   # Jupyter notebook, Spyder or qtconsole
        elif shell == 'TerminalInteractiveShell':
            return False  # Terminal running IPython
        else:
            return False  # Other type (?)
    except NameError:
        return False

**Comment by zivanfi** [comment]
My experiences match the ones described by tunner007 (which is not surprising considering that our environments also seems to match). Displaying inline HTML works for me fine, both from `data.show_batch` (if I work around the downloading part) and also using the example code you pasted. However, `out` will be None in your example, which seems to indicate a bug in the environment instead of in fastprogress:

![image](https://user-images.githubusercontent.com/20930533/68394908-f8c65800-016e-11ea-8b46-dbede19dd930.png)

![image](https://user-images.githubusercontent.com/20930533/68395386-ea2c7080-016f-11ea-86d9-b1d1ebc987a0.png)

Because the bug seems to be elsewhere, I think you can safely close this issue (unless you see some trivial workaround, which may be worth adding).

Thanks to both of you for helping me find the real culprit.

**Comment by sgugger** [comment]
Ok. In this case we can add a test to see if a generated `out` becomes `None` inside `isnotebook`. That way, the progress bar will automatically revert to the console behavior for those enviromnents. Is this what you added @tunner007 ?

**Comment by tunner007** [comment]
> s this

Yes... for me this solves the problem :)

**Comment by zivanfi** [comment]
I continued my investigation and found that in the affected environment IPython is rather old:
```
pip3 freeze | grep ipython

ipython==5.1.0
ipython-genutils==0.2.0
```
I checked the source code of IPython as of this version and found that unlike recent versions, it does not return a display:

- [old implementation](https://github.com/ipython/ipython/blob/7b89b5af27a291d7c91c21b0f58ebf4bdfd06543/IPython/core/display.py#L124)
- [new implementation](https://github.com/ipython/ipython/blob/master/IPython/core/display.py#L321)

This seems to be the root cause of the problem.

**Comment by sgugger** [comment]
Ah ah, in that case a simple test of the ipython version should be enough. Do you know which version starts returning an output?

**Comment by tunner007** [comment]
> I continued my investigation and found that in the affected environment IPython is rather old:
> 
> ```
> pip3 freeze | grep ipython
> 
> ipython==5.1.0
> ipython-genutils==0.2.0
> ```
> 
> I checked the source code of IPython as of this version and found that unlike recent versions, it does not return a display:
> 
> * [old implementation](https://github.com/ipython/ipython/blob/7b89b5af27a291d7c91c21b0f58ebf4bdfd06543/IPython/core/display.py#L124)
> * [new implementation](https://github.com/ipython/ipython/blob/master/IPython/core/display.py#L321)
> 
> This seems to be the root cause of the problem.

Actually i even tried with latest version but faced same problem (versions tested ipython==7.4.0, ipython-7.9.0)

Can you please confirm if upgrading the version works for you ?

**Comment by zivanfi** [comment]
It was added in [this commit](https://github.com/ipython/ipython/commit/c168107a7fdc3862367a535dfdd8effb2cac6dbd#diff-669aef382d43ba6b34e0347434278127R214), and according to the tags listed at the top, it was first released in 6.0.0.

**Comment by zivanfi** [comment]
@tunner007 The reason why upgrading doesn't help is that the interactive REPL prompt ignores the user's enviroment for its dependencies, so even after an upgrade it still uses the old version:

```
> !pip3 freeze | grep ipython
ipython==7.9.0
ipython-genutils==0.2.0
> print(IPython.version_info)
(5, 1, 0, '')
```

**Comment by tunner007** [comment]
> @tunner007 The reason why upgrading doesn't help is that the interactive REPL prompt ignores the user's enviroment for its dependencies, so even after an upgrade it still uses the old version:
> 
> ```
> > !pip3 freeze | grep ipython
> ipython==7.9.0
> ipython-genutils==0.2.0
> > print(IPython.version_info)
> (5, 1, 0, '')
> ```

Got it !

**Comment by sgugger** [comment]
Added the test of IPython version, which should solve the issue. Thanks for your help investigating this bug!

**Comment by sri9s** [comment]
Error on colab, with fastai2, @ learn.fit_one_cycle(4):

AttributeError: ‘NBMasterBar’ object has no attribute ‘out’
AttributeError: ‘NBMasterBar’ object has no attribute ‘start_t’

**Comment by Vijayabhaskar96** [comment]
I'm trying to resume an epoch that was saved by the SaveModelCallback, by using start_epoch=1 but I get this error, Any solutions?

**Comment by veraz00** [comment]
Hello, I have run 
from IPython.display import clear_output, display, HTML
out = display(HTML('<article><header><h1>Testing</h1></header></article>'), display_id=True)
print('out', out)  # here it return None
from IPython import get_ipython
def isnotebook():
    try:
        from google import colab
        return True
    except: pass
    try:
        shell = get_ipython().__class__.__name__
        if shell == 'ZMQInteractiveShell':
            ##added check here for display_id##
            return True   # Jupyter notebook, Spyder or qtconsole
        elif shell == 'TerminalInteractiveShell':
            return False  # Terminal running IPython
        else:
            return False  # Other type (?)
    except NameError:
        return False
print(isnotebook()) and here return True
I am quite new in this area; so what do I do to solve this problem; 
IPython==7.30.1, the newest one
