### ISSUE TITLE
fastprogress in console mode locks up emacs

### ISSUE THREAD

**Issue by rpgoldman** [fastai/fastprogress#43]
I am using fastprogress through emacs -- using emacs's inferior-python-mode and elpy.  When I invoke a function (through PyMC3) that uses fastprogress, it takes over input to the editor until the python call using fastprogress terminates.  Also, it takes the current cursor and pulls it out of whatever editor buffer it was in and puts it into the interactive python buffer.

My guess is that this has something to do with the way that fp is writing its output to the console.  Is it perhaps sending characters to it one at a time to write the progress bar?

**Comment by rpgoldman** [comment]
I'm inclined to close this, since `progressbar=False` solves the problem after the modifications to handling that argument.
Not as good an answer as having a progressbar that works better in text mode, but unless someone's excited about fixing that...
Possibly we could change the progressbar default to `False` if we could tell if we are running in a graphics capable environment? Or swap in a different progressbar?

**Comment by sgugger** [comment]
I don't really know what to do for this issue sadly, so closing...
