### ISSUE TITLE
ImportError: cannot import name 'master_bar' in v0.2.1

### ISSUE THREAD

**Issue by amaiya** [fastai/fastprogress#45]
V0.2.1 of fastprogress released a couple of days ago seems to cause errors when importing `master_bar` and `progress_bar`:

```
>>> from fastprogress import master_bar, progress_bar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'master_bar'
```

Tested on a fresh Ubuntu 18.04 install.

As a workaround, users need to downgrade:  `pip3 install fastprogress==0.1.22`

**Comment by sgugger** [comment]
Yes you must now import them inside fastprogress.fastprogress

**Comment by amaiya** [comment]
OK - thanks.  You should probably update the Usage section in the README to reflect this, as this is what most people look at.

**Comment by sgugger** [comment]
Good point! Will do this ASAP

**Comment by nngo** [comment]
@sgugger I see the same under Windows 10 and using fastprogress 0.2.2 (FYI: I did NOT explictly import this, it is a transitive dependency of importing fastai=1 (1.0.34 installed right now).

```shell
Traceback (most recent call last):
  File "train_mnist.py", line 1, in <module>
    from fastai.script import *
  File "C:\Anaconda3\envs\python37-env\lib\site-packages\fastai\__init__.py", line 1, in <module>
    from .basic_train import *
  File "C:\Anaconda3\envs\python37-env\lib\site-packages\fastai\basic_train.py", line 2, in <module>
    from .torch_core import *
  File "C:\Anaconda3\envs\python37-env\lib\site-packages\fastai\torch_core.py", line 2, in <module>
    from .imports.torch import *
  File "C:\Anaconda3\envs\python37-env\lib\site-packages\fastai\imports\__init__.py", line 1, in <module>
    from .core import *
  File "C:\Anaconda3\envs\python37-env\lib\site-packages\fastai\imports\core.py", line 15, in <module>
    from fastprogress import master_bar, progress_bar
ImportError: cannot import name 'master_bar' from 'fastprogress' (C:\Anaconda3\envs\python37-env\lib\site-packages\fastprogress\__init__.py)
```

So maybe there is a bug in `fastai.core`?

**Comment by sgugger** [comment]
You need to update fastai to the latest version.

**Comment by ruchi11dec** [comment]
> @sgugger I see the same under Windows 10 and using fastprogress 0.2.2 (FYI: I did NOT explictly import this, it is a transitive dependency of importing fastai=1 (1.0.34 installed right now).
> 
> ```shell
> Traceback (most recent call last):
>   File "train_mnist.py", line 1, in <module>
>     from fastai.script import *
>   File "C:\Anaconda3\envs\python37-env\lib\site-packages\fastai\__init__.py", line 1, in <module>
>     from .basic_train import *
>   File "C:\Anaconda3\envs\python37-env\lib\site-packages\fastai\basic_train.py", line 2, in <module>
>     from .torch_core import *
>   File "C:\Anaconda3\envs\python37-env\lib\site-packages\fastai\torch_core.py", line 2, in <module>
>     from .imports.torch import *
>   File "C:\Anaconda3\envs\python37-env\lib\site-packages\fastai\imports\__init__.py", line 1, in <module>
>     from .core import *
>   File "C:\Anaconda3\envs\python37-env\lib\site-packages\fastai\imports\core.py", line 15, in <module>
>     from fastprogress import master_bar, progress_bar
> ImportError: cannot import name 'master_bar' from 'fastprogress' (C:\Anaconda3\envs\python37-env\lib\site-packages\fastprogress\__init__.py)
> ```
> 
> So maybe there is a bug in `fastai.core`?

>Did you got any work around this. I m getting the same error

**Comment by fahadkhan469** [comment]
Hi,

I am trying to do [from fastai.imports import *] in jupyter notebook and getting the same error [ImportError: cannot import name 'master_bar' from 'fastprogress' (C:\Users\fkk17001\AppData\Local\Continuum\anaconda3\lib\site-packages\fastprogress\__init__.py)]

Any solutions?
