### ISSUE TITLE
Missing GitHub Release artifacts since v0.1.22

### ISSUE THREAD

**Issue by andersy005** [fastai/fastprogress#48]
Thank you for this awesome package! 

While working on `fastprogress` recipe for conda-forge in https://github.com/conda-forge/staged-recipes/pull/10658, I noticed some discrepancies between releases on GitHub and the ones available on PyPI. GitHub Release artifacts aren't available since v0.1.22 (November):

- GitHub Releases
![Screen Shot 2020-01-21 at 4 37 51 PM](https://user-images.githubusercontent.com/13301940/72852659-7c6eeb80-3c6c-11ea-8b2f-2a7878ee1a01.png)

- PyPI Releases
![Screen Shot 2020-01-21 at 4 30 46 PM](https://user-images.githubusercontent.com/13301940/72852660-7c6eeb80-3c6c-11ea-9903-f95f7a055a9b.png)

I am wondering if these missing artifacts are available somewhere else? I am asking because I had a hard time building the conda-forge package for `fastprogress` using the `tarbar` from PyPI. 

Thank you!

**Comment by sgugger** [comment]
The nbdev scripts we're using now don't do this automatically, so I guess those are discontinued (I had no idea they existed to be honest).

**Comment by andersy005** [comment]
Thank you for the clarification, @sgugger! I am going to waiting for the next of release of fastprogress before finalizing the conda-forge recipe. .The main issue I was running into had to do with the fact that prior January 2020, `settings.ini` wasn't included in the `MANIFEST.in`. While looking at the current version of `MANIFEST.in`, it appears that this issue has been addressed.
