### ISSUE TITLE
Unexpected kwarg Auto-update TypeError on Colab (Python 3.6)

### ISSUE THREAD

**Issue by eduguiu** [fastai/fastprogress#51]
Hi,  

while going through the course-v3/dl2 notebooks (from 09c onwards) on Google Colab, found this bug. 
TypeError: init() got an unexpected keyword argument 'auto_update'

The origin looks like to be a lack of "auto_update" kwargs. 

![imatge](https://user-images.githubusercontent.com/10409014/74148503-e2181d00-4c05-11ea-8314-64924121fbed.png)

Commenting the "auto-update=False " is enought to bypass the error. 

![imatge](https://user-images.githubusercontent.com/10409014/74026338-42108880-49a6-11ea-835b-b21497aaf87a.png)

I've checked the installed version of fastprogress and it happens to be 0.2.2

Thanks,

Ed

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-183-36204b60e23f> in <module>()
----> 1 learn.fit(40, cbsched)

5 frames

/content/drive/My Drive/colab/course-v3/nbs/dl2/exp/nb_09b.py in fit(self, epochs, cbs, reset_opt)
     69             self.do_begin_fit(epochs)
     70             for epoch in range(epochs):
---> 71                 self.do_begin_epoch(epoch)
     72                 if not self('begin_epoch'): self.all_batches()
     73 

/content/drive/My Drive/colab/course-v3/nbs/dl2/exp/nb_09b.py in do_begin_epoch(self, epoch)
     58     def do_begin_epoch(self, epoch):
     59         self.epoch,self.dl = epoch,self.data.train_dl
---> 60         return self('begin_epoch')
     61 
     62     def fit(self, epochs, cbs=None, reset_opt=False):

/content/drive/My Drive/colab/course-v3/nbs/dl2/exp/nb_09b.py in __call__(self, cb_name)
     90         res = False
     91         assert cb_name in self.ALL_CBS
---> 92         for cb in sorted(self.cbs, key=lambda x: x._order): res = cb(cb_name) and res
     93         return res
     94 

/content/drive/My Drive/colab/course-v3/nbs/dl2/exp/nb_05b.py in __call__(self, cb_name)
     19     def __call__(self, cb_name):
     20         f = getattr(self, cb_name, None)
---> 21         if f and f(): return True
     22         return False
     23 

/content/drive/My Drive/colab/course-v3/nbs/dl2/exp/nb_09c.py in begin_epoch(self)
     45     def after_fit(self): self.mbar.on_iter_end()
     46     def after_batch(self): self.pb.update(self.iter)
---> 47     def begin_epoch   (self): self.set_pb()
     48     def begin_validate(self): self.set_pb()
     49 

/content/drive/My Drive/colab/course-v3/nbs/dl2/exp/nb_09c.py in set_pb(self)
     49 
     50     def set_pb(self):
---> 51         self.pb = progress_bar(self.dl, parent=self.mbar, auto_update=False)
     52         self.mbar.update(self.epoch)

TypeError: __init__() got an unexpected keyword argument 'auto_update'
--------------------------------------------------

**Comment by sgugger** [comment]
This needs to be fixed in course-v3 not here. Please open an issue there if I forget to fix it later today.

**Comment by eduguiu** [comment]
merci Sylvain.
Je demarre juste et je voulais vous aider. Ainsi que tester si je pouvais
lancer un cable.
courage avec le CoViD et merci pour tout.

cdt,

Eduard


Le sam. 28 mars 2020 à 14:33, Sylvain Gugger <notifications@github.com> a
écrit :
