### ISSUE TITLE
ImportError: cannot import name 'master_bar'

### ISSUE THREAD

**Issue by BlockchainRev** [fastai/fastprogress#58]
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-283c0d40bede> in <module>
----> 1 from fastai.vision import *
      2 from fastai.metrics import error_rate

~\Anaconda3\envs\fastai\lib\site-packages\fastai\__init__.py in <module>
----> 1 from .basic_train import *
      2 from .callback import *
      3 #from .callbacks import *
      4 from .core import *
      5 from .basic_data import *

~\Anaconda3\envs\fastai\lib\site-packages\fastai\basic_train.py in <module>
      1 "Provides basic training and validation with `Learner`"
----> 2 from .torch_core import *
      3 from .basic_data import *
      4 from .callback import *
      5 

~\Anaconda3\envs\fastai\lib\site-packages\fastai\torch_core.py in <module>
      1 "Utility functions to help deal with tensors"
----> 2 from .imports.torch import *
      3 from .core import *
      4 
      5 AffineMatrix = Tensor

~\Anaconda3\envs\fastai\lib\site-packages\fastai\imports\__init__.py in <module>
----> 1 from .core import *
      2 from .torch import *

~\Anaconda3\envs\fastai\lib\site-packages\fastai\imports\core.py in <module>
     13 from dataclasses import dataclass, field
     14 from enum import Enum, IntEnum
---> 15 from fastprogress import master_bar, progress_bar
     16 from functools import partial, reduce, singledispatch
     17 from pdb import set_trace

ImportError: cannot import name 'master_bar'
`
What's happening?

**Comment by sgugger** [comment]
Make sure you have the latest version of fastai. I'll also make a release of fastprogress since the generic fix is in master.
