### ISSUE TITLE
Progress Bar on Pycharm?

### ISSUE THREAD

**Issue by bomcon123456** [fastai/fastprogress#61]
Hi I'm currently using Pycharm to run remote jupyter server, but when I'm training (using fastai2), the progress bar simply grey and not running at all (the train still ran and finished)
Thank you!
![ảnh](https://user-images.githubusercontent.com/20278911/79966111-230a9880-84b7-11ea-8a6f-e467fa334c7f.png)

**Comment by sgugger** [comment]
It seem simple widgets don't work in Pycharm so you should use the console behavior:
```
from fastprogress.fastprogress import force_console_behavior
master_bar, progress_bar = force_console_behavior()
```

**Comment by aljungberg** [comment]
Just for future reference, the reason PyCharm output with the regular progress bar doesn't work is that `self.out.update` does nothing in PyCharm. I found a number of issues in the PyCharm bug tracker which seem to confirm that progressively updating display output using `display_handle = display(..., display_id=True)` and `display_handle.update()` has no effect.

You can render the HTML just fine like this:

```
from IPython.display import clear_output, display, HTML
display(HTML(mb.html_code))
```

where `mb` is the master bar. This renders the correct output -- but there seems to be no way to make it interactive/animated such that it updates over time in PyCharm.

One of the jetbrains bug reports: https://youtrack.jetbrains.com/issue/DS-3383/IPythondisplay-update-problem
