### ISSUE TITLE
Master bar not showing in console

### ISSUE THREAD

**Issue by tcapelle** [fastai/fastprogress#63]
The master bar is not showing on console.
```python
bar = master_bar(range(10))
for e in bar:
    for i in progress_bar(range(10), parent=bar):
        sleep(0.05)
```
On the notebook I get what I want, but not on the terminal.
![image](https://user-images.githubusercontent.com/18441985/82228626-a76f0080-9929-11ea-8fdb-c4957a5b708e.png)
But on console only get the child bar:
![image](https://user-images.githubusercontent.com/18441985/82228724-ca99b000-9929-11ea-8fa7-4d96b9b4f022.png)

**Comment by sgugger** [comment]
Yes that is expected. You can't flush more than one line so you can't have a nested progress bar in console mode. You'll get one like per epoch instead, this is the intended behavior.
